# Generated by Django 5.0.6 on 2025-08-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='wifisession',
            index=models.Index(fields=['phone_number'], name='core_wifise_phone_n_b26c97_idx'),
        ),
        migrations.AddIndex(
            model_name='wifisession',
            index=models.Index(fields=['token'], name='core_wifise_token_ad01d3_idx'),
        ),
    ]
