# Generated by Django 5.0.6 on 2025-08-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.RemoveIndex(
            model_name='wifisession',
            name='core_wifise_phone_n_b26c97_idx',
        ),
        migrations.RemoveIndex(
            model_name='wifisession',
            name='core_wifise_token_ad01d3_idx',
        ),
        migrations.RemoveField(
            model_name='wifisession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='wifisession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wifisession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wifisession',
            name='token',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
