# Generated by Django 5.0.6 on 2025-08-07 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='mikrotik_password',
            new_name='savanna_password',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='mikrotik_username',
            new_name='savanna_username',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mikrotik_host',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='mikrotik_profile_name',
        ),
        migrations.AddField(
            model_name='company',
            name='savanna_host',
            field=models.CharField(default='192.168.1.1', max_length=255),
        ),
        migrations.AddField(
            model_name='wifisession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wifisession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='airtel_business_account',
            field=models.CharField(blank=True, help_text='The phone number linked to the Airtel Business Account.', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='airtel_consumer_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='airtel_consumer_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='company',
            field=models.ForeignKey(default='f6323c90-0b61-4122-83b5-7c0a6b7d2f9d', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_minutes',
            field=models.IntegerField(help_text='Duration in minutes.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wifisession',
            name='company',
            field=models.ForeignKey(default='f6323c90-0b61-4122-83b5-7c0a6b7d2f9d', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wifisession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wifisession',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='wifisession',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plan'),
        ),
        migrations.AlterField(
            model_name='wifisession',
            name='token',
            field=models.CharField(blank=True, default='f6323c90-0b61-4122-83b5-7c0a6b7d2f9d', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.wifisession')),
            ],
        ),
    ]
