# Generated by Django 5.0.6 on 2025-08-07 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_timestamp_payment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='airtel_access_token',
        ),
        migrations.RemoveField(
            model_name='company',
            name='airtel_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_default',
        ),
        migrations.AddField(
            model_name='company',
            name='airtel_business_account',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wifisession',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wifisession',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan'),
        ),
        migrations.AlterField(
            model_name='wifisession',
            name='token',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
